name: Expo Build-web
on:
  push:
    branches:
      - master
jobs:
  ci:
    name: Daily Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
      - run: yarn install
      - run: yarn test
      - run: expo build:web
